config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'words#index'
  get '/:id' => 'words#show'

  class OnlyAjaxRequests
    def matches?(request)
      request.xhr?
    end
  end

match '/' => 'words#listwords', :constraints => OnlyAjaxRequests.new, via: :post, defaults: {format: 'json'}

end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  def listwords
    render json: Word.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word, :wordtype, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Devil's Dictionary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<h1>The Devil's Dictionary</h1>
<%= yield %>
</div>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :wordtype %><br>
    <%= f.number_field :wordtype %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Preface</h3>
<div class="dic-description">
<p>
_The Devil's Dictionary_ was begun in a weekly paper in 1881, and was
continued in a desultory way at long intervals until 1906.  In that
year a large part of it was published in covers with the title _The
Cynic's Word Book_, a name which the author had not the power to
reject or happiness to approve.  To quote the publishers of the
present work:
</p>
<p>
"This more reverent title had previously been forced upon him by
the religious scruples of the last newspaper in which a part of the
work had appeared, with the natural consequence that when it came out
in covers the country already had been flooded by its imitators with a
score of 'cynic' books -- _The Cynic's This_, _The Cynic's That_, and
_The Cynic's t'Other_.  Most of these books were merely stupid, though
some of them added the distinction of silliness.  Among them, they
brought the word 'cynic' into disfavor so deep that any book bearing
it was discredited in advance of publication."
</p>
<p>
Meantime, too, some of the enterprising humorists of the country
had helped themselves to such parts of the work as served their needs,
and many of its definitions, anecdotes, phrases and so forth, had
become more or less current in popular speech.  This explanation is
made, not with any pride of priority in trifles, but in simple denial
of possible charges of plagiarism, which is no trifle.  In merely
resuming his own the author hopes to be held guiltless by those to
whom the work is addressed -- enlightened souls who prefer dry wines
to sweet, sense to sentiment, wit to humor and clean English to slang.
</p>
<p>
A conspicuous, and it is hoped not unpleasant, feature of the book
is its abundant illustrative quotations from eminent poets, chief of
whom is that learned and ingenius cleric, Father Gassalasca Jape,
S.J., whose lines bear his initials.  To Father Jape's kindly
encouragement and assistance the author of the prose text is greatly
indebted.
</p>
<p>
A.B.
</p>
</div>
<h3>Dictionary</h3>
<div class="words-wrap">
	<ul id="word-table">
	</ul>
</div>

<br>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<div id="single-word">
	<h4><%= @word.word %></h4>
	<h5><%= @word.wordtype %></h5>
	<p><%= @word.description %></p>
	<div class="flickr-photo"></div>
</div>